spring:
  application:
    name: springboot-stop-tool
  #数据库的连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/park
    username: root
    password: text123
    #文件上传的配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true

#mybatis配置
mybatis:
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名
    map-underscore-to-camel-case: true

#阿里云oss配置
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tCQ5KaLnvqpRLFLhfpQ
    accessKeySecret: iEjdz9l8BMFPtgF9AuJlBEqyT5wb1z
    bucketName: array-chen

#spring事物管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

server:
  port: 8080

